const API = 'https://api.github.com/repos/mobconnect/Sungcodes/contents';
const RAW = 'https://github.com/mobconnect/Sungcodes/tree/main';
const $ = selector => document.querySelector(selector);
const artistsEl = $('#artists'); let artists = [];
const escapeHtml = value => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const slug = value => value.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
function render(query = '') { const term = slug(query); const visible = artists.filter(a => !term || slug(a.name).includes(term) || a.files.some(f => slug(f.name).includes(term))); $('#result-count').textContent = `${visible.length} artist${visible.length === 1 ? '' : 's'}`; $('#clear').hidden = !query; $('#empty').hidden = visible.length > 0; artistsEl.innerHTML = visible.map(a => { const files = a.files.filter(f => !term || slug(a.name).includes(term) || slug(f.name).includes(term)); return `<article class="card"><div class="card-top"><div class="avatar">${escapeHtml(a.name[0].toUpperCase())}</div><div><h2>${escapeHtml(a.name)}</h2><p>${a.files.length} code file${a.files.length === 1 ? '' : 's'}</p></div></div><ul>${files.slice(0, 5).map(f => `<li><a href="${f.html_url}" target="_blank" rel="noreferrer">♪ ${escapeHtml(f.name)}</a></li>`).join('')}</ul><a class="folder" href="${RAW}/${encodeURIComponent(a.name)}" target="_blank" rel="noreferrer">Open collection ↗</a></article>`; }).join(''); }
async function loadLibrary() { try { const response = await fetch(API, {headers: {Accept: 'application/vnd.github+json'}}); if (!response.ok) throw new Error(`GitHub returned ${response.status}`); const entries = await response.json(); artists = await Promise.all(entries.filter(e => e.type === 'dir').map(async folder => { const r = await fetch(folder.url); const files = r.ok ? await r.json() : []; return {name: folder.name, files: files.filter(f => f.type === 'file')}; })); artists.sort((a,b) => a.name.localeCompare(b.name)); $('#status').textContent = ' · Live from GitHub'; render(); } catch (error) { $('#result-count').textContent = 'Library unavailable'; $('#status').textContent = ' · Try GitHub directly'; artistsEl.innerHTML = `<div class="error"><h2>Could not load the library</h2><p>${escapeHtml(error.message)}. <a href="https://github.com/mobconnect/Sungcodes">Browse GitHub</a>.</p></div>`; } }
$('#search').addEventListener('input', e => render(e.target.value)); $('#clear').addEventListener('click', () => { $('#search').value = ''; render(); }); document.addEventListener('keydown', e => { if (e.key === '/' && document.activeElement !== $('#search')) { e.preventDefault(); $('#search').focus(); } });
function generateLyrics() { const theme = $('#theme').value.trim() || 'finding your way'; const mood = $('#mood').value.toLowerCase(); const genre = $('#genre').value.trim() || 'indie pop'; const hook = $('#hook').value.trim() || `I keep moving through the ${theme}`; const ideas = $('#ideas').value.trim(); const extra = ideas ? `\n${ideas}` : ''; const draft = `[Verse 1]\nStreetlights draw a map across the night\nSmall sparks gather, turning dark to bright\nEvery step becomes a choice I make\nI am more than all the roads I take\n\n[Pre-Chorus]\nI hear a quiet rhythm underneath\nA little brave, a little out of breath\n\n[Chorus]\n${hook}\nWith a ${mood} heart and an open sky\nI will write the next line as I go\nLet the new day find me moving slow\n\n[Verse 2]\nI keep the lessons, leave the weight behind\nMake a little room for what I find\n${extra}\n\n[Bridge]\nNo borrowed words, no yesterday to prove\nJust my own voice learning how to move\n\n[Final Chorus]\n${hook}\nThis is my beginning, this is mine\nA brand-new melody between the lines\n\nStyle note: original ${mood} ${genre} draft`; $('#lyrics').textContent = draft; $('#draft').hidden = false; }
$('#generate').addEventListener('click', generateLyrics); $('#copy').addEventListener('click', async () => { await navigator.clipboard.writeText($('#lyrics').textContent); $('#copy').textContent = 'Copied ✓'; setTimeout(() => $('#copy').textContent = 'Copy lyrics', 1600); }); $('#download').addEventListener('click', () => { const blob = new Blob([$('#lyrics').textContent], {type: 'text/plain'}); const link = Object.assign(document.createElement('a'), {href: URL.createObjectURL(blob), download: 'sungcodes-original-lyrics.txt'}); link.click(); URL.revokeObjectURL(link.href); }); loadLibrary();
