// Sungcodes experience enhancements: featured discovery, player, filters, stats, accessibility and caching.
(() => {
  const $ = (selector, root = document) => root.querySelector(selector);
  const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
  const esc = value => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const featuredSongs = [
    { title: 'Midnight Windows', artist: 'Original community work', genre: 'Indie pop', mood: 'Reflective', tempo: '96 BPM', description: 'A quiet song about finding direction after a difficult season.', lyrics: '[Verse]\nStreetlights draw a map across the night\nSmall sparks gather, turning dark to bright\n\n[Chorus]\nI find a window in the midnight glow\nAnd take one more brave step to go' },
    { title: 'Small Sparks', artist: 'Sungcodes Studio', genre: 'Acoustic', mood: 'Hopeful', tempo: '104 BPM', description: 'An uplifting draft about rebuilding confidence.', lyrics: '[Verse]\nI keep the lessons, leave the weight behind\nMake a little room for what I find\n\n[Chorus]\nSmall sparks are enough to start a fire\nOne true note can lift me higher' }
  ];
  const style = document.createElement('style');
  style.textContent = `.featured,.song-viewer,.player,.filters,.display-tools{background:var(--surface,#fff);border:1px solid var(--line);border-radius:15px;padding:25px;margin-bottom:32px}.section-heading,.player,.player-info,.player-controls,.viewer-actions,.display-tools{display:flex;align-items:center;gap:14px}.section-heading{justify-content:space-between}.featured-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}.featured-card{padding:20px;border:1px solid var(--line);border-radius:12px;background:color-mix(in srgb,var(--cream) 75%,white)}.featured-card h3{margin:.55rem 0}.featured-card p{color:var(--muted)}.song-badge{font-size:.75rem;color:var(--purple);font-weight:800;text-transform:uppercase;letter-spacing:.08em}.song-meta{display:flex;justify-content:space-between;color:var(--muted);font-size:.85rem;margin:15px 0}.song-viewer[hidden]{display:none}.viewer-lyrics{white-space:pre-wrap;line-height:1.9;max-width:720px;margin:1.5rem auto;padding:2rem;border-left:4px solid var(--purple);background:#f5f0fb;border-radius:12px}.lyric-line{padding:.25rem .5rem;border-radius:.35rem}.lyric-line.active{background:#e2d1fa;color:#24163e;font-weight:800}.player{position:sticky;bottom:12px;z-index:5;box-shadow:0 8px 25px #0002}.player-art{display:grid;place-items:center;width:42px;height:42px;border-radius:10px;background:var(--purple);color:#fff;font-weight:800}.player-info{flex-direction:column;align-items:flex-start;min-width:150px}.player-info span{color:var(--muted);font-size:.85rem}.player-controls button{border:0;background:transparent;cursor:pointer;font-size:1.15rem}.player progress{flex:1}.filters,.display-tools{flex-wrap:wrap}.filters label{font-size:.85rem;font-weight:700}.filters select{display:block;margin-top:5px;padding:8px;border:1px solid var(--line);border-radius:7px;background:var(--surface,#fff);color:var(--ink)}.writing-stats{display:flex;flex-wrap:wrap;gap:16px;color:var(--muted);font-size:.85rem;margin:8px 0 18px}.dark{--surface:#241e2b}.dark .featured-card,.dark .viewer-lyrics{background:#30283a}.large-text{font-size:18px}.reduced-motion *{transition:none!important;animation:none!important;scroll-behavior:auto!important}:focus-visible{outline:3px solid #f0b429;outline-offset:3px}@media(max-width:650px){.player{flex-wrap:wrap}.player progress{flex-basis:100%}.display-tools{align-items:stretch}.viewer-actions{flex-wrap:wrap}}`;
  document.head.appendChild(style);
  const main = $('.main'); if (!main) return;
  const featured = document.createElement('section'); featured.className = 'featured'; featured.innerHTML = `<div class="section-heading"><div><p class="eyebrow">Explore something new</p><h2 id="featured-title">Featured Sungcodes</h2></div><button id="shuffleFeatured" class="text-button" type="button">Shuffle</button></div><div id="featuredGrid" class="featured-grid"></div>`;
  const viewer = document.createElement('section'); viewer.id = 'songViewer'; viewer.className = 'song-viewer'; viewer.hidden = true; viewer.innerHTML = `<button id="closeSongViewer" class="text-button" type="button">← Back to library</button><p id="viewerStatus" class="eyebrow"></p><h2 id="viewerTitle"></h2><p id="viewerMeta" class="muted"></p><pre id="viewerLyrics" class="viewer-lyrics"></pre><div class="viewer-actions"><button id="viewerPreview" class="button" type="button">Preview</button><button id="viewerCopy" class="button secondary" type="button">Copy lyrics</button><button id="viewerDownload" class="button secondary" type="button">Download</button></div>`;
  const filters = document.createElement('section'); filters.className = 'filters'; filters.innerHTML = `<label>Genre<select id="genreFilter"><option value="">All genres</option><option value="pop">Pop</option><option value="acoustic">Acoustic</option><option value="rock">Rock</option><option value="indie">Indie</option></select></label><label>Mood<select id="moodFilter"><option value="">All moods</option><option value="hopeful">Hopeful</option><option value="reflective">Reflective</option><option value="energetic">Energetic</option></select></label><label>Sort<select id="sortSongs"><option value="name">Name</option><option value="random">Random</option></select></label>`;
  const tools = document.createElement('section'); tools.className = 'display-tools'; tools.innerHTML = `<button id="themeToggle" type="button">Dark mode</button><button id="textSizeToggle" type="button">Larger text</button><button id="motionToggle" type="button">Reduce motion</button>`;
  const player = document.createElement('section'); player.className = 'player'; player.setAttribute('aria-label','Sungcode player'); player.innerHTML = `<div class="player-art"><span id="playerInitial">S</span></div><div class="player-info"><strong id="playerTitle">No Sungcode selected</strong><span id="playerLine">Choose Preview to begin</span></div><div class="player-controls"><button id="playerPlay" type="button" aria-label="Play">▶</button><button id="playerPause" type="button" aria-label="Pause">Ⅱ</button><button id="playerStop" type="button" aria-label="Stop">■</button></div><progress id="playerProgress" value="0" max="100"></progress>`;
  const toolbar = $('.toolbar', main); [featured, viewer, tools, filters].forEach(section => main.insertBefore(section, toolbar)); main.appendChild(player);
  const stats = document.createElement('div'); stats.className = 'writing-stats'; stats.innerHTML = '<span id="wordCount">0 words</span><span id="lineCount">0 lines</span><span id="durationEstimate">About 0:00</span>'; const creatorLyrics = $('#creatorLyrics'); if (creatorLyrics) creatorLyrics.parentNode.insertBefore(stats, creatorLyrics);
  let currentSong = null; let timerIds = [];
  function renderFeatured(items = featuredSongs) { $('#featuredGrid').innerHTML = items.map((song, index) => `<article class="featured-card"><span class="song-badge">${esc(song.mood)}</span><h3>${esc(song.title)}</h3><p>${esc(song.description)}</p><div class="song-meta"><span>${esc(song.genre)}</span><span>${esc(song.tempo)}</span></div><button class="button secondary" data-featured="${index}" type="button">Open Sungcode</button></article>`).join(''); $$('#featuredGrid [data-featured]').forEach(button => button.addEventListener('click', () => openSong(items[Number(button.dataset.featured)]))); }
  function openSong(song) { currentSong = song; $('#viewerStatus').textContent = song.artist; $('#viewerTitle').textContent = song.title; $('#viewerMeta').textContent = `${song.genre} · ${song.mood} · ${song.tempo}`; $('#viewerLyrics').innerHTML = song.lyrics.split(/\r?\n/).map(line => `<span class="lyric-line">${esc(line) || '&nbsp;'}</span>`).join('\n'); viewer.hidden = false; viewer.scrollIntoView({behavior: document.body.classList.contains('reduced-motion') ? 'auto' : 'smooth'}); $('#playerTitle').textContent = song.title; $('#playerLine').textContent = song.artist; $('#playerInitial').textContent = song.title[0]; }
  function stop() { timerIds.forEach(clearTimeout); timerIds = []; if ('speechSynthesis' in window) speechSynthesis.cancel(); $('#playerProgress').value = 0; $$('.lyric-line').forEach(line => line.classList.remove('active')); $('#playerLine').textContent = currentSong ? currentSong.artist : 'Choose Preview to begin'; }
  function play(song = currentSong) { if (!song) return; stop(); currentSong = song; openSong(song); const lines = $$('.lyric-line'); const words = song.lyrics.split(/\s+/).length; lines.forEach((line, index) => { const id = setTimeout(() => { lines.forEach(item => item.classList.remove('active')); line.classList.add('active'); $('#playerProgress').value = ((index + 1) / lines.length) * 100; $('#playerLine').textContent = `Line ${index + 1} of ${lines.length}`; if ('speechSynthesis' in window) speechSynthesis.speak(Object.assign(new SpeechSynthesisUtterance(line.textContent.trim()), {rate:.85})); }, index * Math.max(250, Math.round(60000 / (Number.parseInt(song.tempo) || 100)))); timerIds.push(id); }); }
  $('#closeSongViewer').addEventListener('click', () => { stop(); viewer.hidden = true; }); $('#viewerPreview').addEventListener('click', () => play()); $('#viewerCopy').addEventListener('click', async () => { if (currentSong) { await navigator.clipboard.writeText(currentSong.lyrics); $('#viewerCopy').textContent = 'Copied ✓'; setTimeout(() => $('#viewerCopy').textContent = 'Copy lyrics', 1500); } }); $('#viewerDownload').addEventListener('click', () => { if (!currentSong) return; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([currentSong.lyrics], {type:'text/plain'})); link.download = `${currentSong.title.toLowerCase().replace(/[^a-z0-9]+/g,'-')}.txt`; link.click(); }); $('#playerPlay').addEventListener('click', () => play()); $('#playerPause').addEventListener('click', () => { if ('speechSynthesis' in window) speechSynthesis.pause(); }); $('#playerStop').addEventListener('click', stop); $('#shuffleFeatured').addEventListener('click', () => renderFeatured([...featuredSongs].sort(() => Math.random() - .5)));
  function updateStats() { if (!creatorLyrics) return; const text = creatorLyrics.value.trim(); const words = text ? text.split(/\s+/).length : 0; const lines = text ? text.split(/\r?\n/).filter(Boolean).length : 0; const seconds = Math.round(words / 100 * 60); $('#wordCount').textContent = `${words} words`; $('#lineCount').textContent = `${lines} lines`; $('#durationEstimate').textContent = `About ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`; }
  function filterCards() { const genre = $('#genreFilter').value; const mood = $('#moodFilter').value; $$('.card').forEach(card => { const text = card.textContent.toLowerCase(); card.hidden = Boolean((genre && !text.includes(genre)) || (mood && !text.includes(mood)); }); }
  $('#genreFilter').addEventListener('change', filterCards); $('#moodFilter').addEventListener('change', filterCards); $('#sortSongs').addEventListener('change', event => { if (event.target.value === 'random') $$('.grid').forEach(grid => [...grid.children].sort(() => Math.random()-.5).forEach(card => grid.appendChild(card))); }); if (creatorLyrics) creatorLyrics.addEventListener('input', updateStats);
  const savedTheme = localStorage.getItem('sungcodes-theme'); if (savedTheme === 'dark') document.body.classList.add('dark'); $('#themeToggle').addEventListener('click', () => { document.body.classList.toggle('dark'); localStorage.setItem('sungcodes-theme', document.body.classList.contains('dark') ? 'dark' : 'light'); }); $('#textSizeToggle').addEventListener('click', () => document.body.classList.toggle('large-text')); $('#motionToggle').addEventListener('click', () => document.body.classList.toggle('reduced-motion'));
  renderFeatured(); updateStats();
})();
